version: '3'
services:
  bot:
    build: .
    restart: always
    environment:
      - DISCORD_BOT_TOKEN=YOUR_DISCORD_BOT_TOKEN
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
